fix clang comments
Signed-off-by: AdityaPandeyCN <adityapand3y666@gmail.com>

diff --git a/.github/workflows/clang-tidy-review-post.yml b/.github/workflows/clang-tidy-review-post.yml
--- a/.github/workflows/clang-tidy-review-post.yml
+++ b/.github/workflows/clang-tidy-review-post.yml
@@ -11,26 +11,21 @@ permissions:
   pull-requests: write
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.event.workflow_run.pull_requests[0].number }}
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
   cancel-in-progress: true
 
 jobs:
-  post-comments:
-    # Only run if the triggering workflow was from a pull request
-    if: github.event.workflow_run.event == 'pull_request'
+  build:
     runs-on: ubuntu-latest
-    
+
     steps:
       - name: Post review comments
         id: post-review
         uses: ZedThree/clang-tidy-review/post@v0.21.0
         with:
           max_comments: 10
-          
-      # Fail if there are any clang-tidy warnings
-      - name: Check for issues
-        if: steps.post-review.outputs.total_comments > 0
-        run: |
-          echo "::error::Found ${{ steps.post-review.outputs.total_comments }} clang-tidy issues"
-          exit 1
+
+       # If there are any comments, fail the check
+      - if: steps.post-review.outputs.total_comments > 0
+        run: exit 1
 
